defaults: &defaults
  adapter: postgresql
  min_messages: WARNING
  encoding: unicode
  username: rakib
  password: rakib
  pool: 5
  timeout: 5000

development:
  <<: *defaults
  database: envc_development